"""
app/models/db/agent_proposal.py — AgentProposal table.

Tracks every StrategyIR mutation proposed by the agentic loop.

Lifecycle (Phase 4 §3):
  pending_backtest → backtest_done → (human approves) →
  pending_paper → paper_done → (human approves) → approved (live)

  At any stage: → rejected  (human rejects with reason)

Architecture constraints enforced here (Part 3 §Phase 4):
  1. The agent NEVER touches capital.allocated — the capital block is
     read-only to any proposal; CapitalAllocatorRule remains human-set.
  2. Every version of every manifest is traceable to a proposal_id +
     agent_run_id — closing the schema/version policy gap from Part 3 §2.
  3. Human approval is required at TWO gates: backtest→paper and paper→live.
     The status enum encodes these gates structurally so no application code
     can skip them without an explicit column transition.

Alembic migration: 008_add_agent_proposal.py
"""

from __future__ import annotations

import datetime
import enum

from sqlalchemy import DateTime, Enum, Integer, JSON, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.models.db.base import Base


class ProposalStatus(str, enum.Enum):
    """
    Lifecycle states of an agent proposal.

    Transitions (valid forward-only paths):
        pending_backtest → backtest_done → pending_paper → paper_done → approved
        Any state except approved → rejected
    """
    PENDING_BACKTEST = "pending_backtest"
    BACKTEST_DONE    = "backtest_done"
    PENDING_PAPER    = "pending_paper"
    PAPER_DONE       = "paper_done"
    APPROVED         = "approved"
    REJECTED         = "rejected"


class AgentProposal(Base):
    """
    One row per StrategyIR mutation proposed by the agent.

    Fields
    ------
    proposal_id     : UUID-style string PK (generated by AgentLoopService).
    strategy_id     : References strategy_manifests.strategy_id (soft FK).
    parent_version  : Manifest version the mutation is based on (lineage anchor).
    proposed_graph  : The mutated StrategyIR JSON — ONLY nodes/edges, NO capital.
    mutation_summary: Human-readable description of the change (from AgentIRMutation.reason).
    agent_run_id    : Identifies the agent invocation for full lineage tracing.
    status          : Current lifecycle state (see ProposalStatus).
    backtest_metrics: JSON result from BacktestEngine.summary() after run_backtest().
    paper_metrics   : JSON P&L captured during paper trading phase.
    approved_by     : Free-text identifier of the human who approved (e.g. username, "human").
    rejection_reason: Human-provided reason if status=rejected.
    created_at      : Row creation timestamp.
    updated_at      : Last modification timestamp (updated on every status transition).
    """

    __tablename__ = "agent_proposals"

    # ── Identity ──────────────────────────────────────────────────────────────
    proposal_id: Mapped[str] = mapped_column(
        Text,
        primary_key=True,
        comment="UUID string generated by AgentLoopService at proposal time",
    )

    # ── Foreign reference ─────────────────────────────────────────────────────
    strategy_id: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        index=True,
        comment="References strategy_manifests.strategy_id (soft FK — no cascade)",
    )
    parent_version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        comment="strategy_manifest.version this proposal mutates — lineage anchor",
    )

    # ── Mutation payload ──────────────────────────────────────────────────────
    proposed_graph: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
        comment=(
            "Mutated StrategyIR — {nodes: [...], edges: [...]}. "
            "NEVER contains capital/risk overrides — those remain human-set."
        ),
    )
    mutation_summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Agent-provided rationale for this mutation (from AgentIRMutation.reason)",
    )

    # ── Lineage ───────────────────────────────────────────────────────────────
    agent_run_id: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        index=True,
        comment="Identifies the agent invocation — links all proposals from one run",
    )

    # ── Lifecycle ─────────────────────────────────────────────────────────────
    status: Mapped[str] = mapped_column(
        Enum(ProposalStatus, values_callable=lambda x: [e.value for e in x]),
        nullable=False,
        default=ProposalStatus.PENDING_BACKTEST.value,
        comment="Current lifecycle state — see ProposalStatus enum",
    )

    # ── Results ───────────────────────────────────────────────────────────────
    backtest_metrics: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
        comment="Output of BacktestEngine.summary() — populated after run_backtest()",
    )
    paper_metrics: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
        comment="P&L/trade stats captured during paper trading phase",
    )

    # ── Human approval ────────────────────────────────────────────────────────
    approved_by: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Human approver identifier — required before promote_to_paper/live",
    )
    rejection_reason: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Human-provided reason when status=rejected",
    )

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime,
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime,
        server_default=func.now(),
        nullable=False,
    )

    # ── Helpers ───────────────────────────────────────────────────────────────

    @property
    def is_terminal(self) -> bool:
        """Return True if the proposal is in a terminal state (approved or rejected)."""
        return self.status in (
            ProposalStatus.APPROVED.value,
            ProposalStatus.REJECTED.value,
        )

    @property
    def can_approve_to_paper(self) -> bool:
        """Human may approve backtest result and move to paper stage."""
        return self.status == ProposalStatus.BACKTEST_DONE.value

    @property
    def can_promote_to_live(self) -> bool:
        """Human may approve paper result and move to live (approved)."""
        return self.status == ProposalStatus.PAPER_DONE.value

    def __repr__(self) -> str:
        return (
            f"AgentProposal(id={self.proposal_id!r}, "
            f"strategy={self.strategy_id!r}, "
            f"status={self.status!r}, "
            f"run={self.agent_run_id!r})"
        )
