"""Add trade_mode column to signals, trades, and order_events tables.

Revision ID: 002
Revises: 001
Create Date: 2026-05-27

Adds a nullable TEXT column `trade_mode` to three tables to track whether
each record was generated by a PAPER or LIVE trade execution.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "002"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── signals ─────────────────────────────────────────────────────────
    # Tracks which trade mode caused this signal to progress to an entry.
    # NULL = recorded before this migration, or signal never led to a trade.
    with op.batch_alter_table("signals") as batch_op:
        batch_op.add_column(
            sa.Column("trade_mode", sa.Text, nullable=True)
        )

    # ── trades ──────────────────────────────────────────────────────────
    # PAPER or LIVE — set when a trade is opened. Never NULL after this migration.
    with op.batch_alter_table("trades") as batch_op:
        batch_op.add_column(
            sa.Column("trade_mode", sa.Text, nullable=True)
        )

    # ── order_events ─────────────────────────────────────────────────────
    # PAPER or LIVE — matches the trade that generated this order event.
    with op.batch_alter_table("order_events") as batch_op:
        batch_op.add_column(
            sa.Column("trade_mode", sa.Text, nullable=True)
        )


def downgrade() -> None:
    with op.batch_alter_table("order_events") as batch_op:
        batch_op.drop_column("trade_mode")

    with op.batch_alter_table("trades") as batch_op:
        batch_op.drop_column("trade_mode")

    with op.batch_alter_table("signals") as batch_op:
        batch_op.drop_column("trade_mode")
