"""Add signal_snapshots table

Revision ID: 03f052fed285
Revises: 003
Create Date: 2026-05-29 11:47:02.756351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f052fed285'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("datetime('now')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_snapshots_signal_id', 'signal_snapshots', ['signal_id'], unique=False)
    op.create_index('idx_signal_snapshots_symbol', 'signal_snapshots', ['symbol'], unique=False)
    op.create_index('idx_signal_snapshots_time', 'signal_snapshots', ['snapshot_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_signal_snapshots_time', table_name='signal_snapshots')
    op.drop_index('idx_signal_snapshots_symbol', table_name='signal_snapshots')
    op.drop_index('idx_signal_snapshots_signal_id', table_name='signal_snapshots')
    op.drop_table('signal_snapshots')
    # ### end Alembic commands ###
